---
- name: Apache modules enabled
  apache2_module: state=present name={{ item }}
  with_items:
    - proxy
    - proxy_http
    - ssl
    - rewrite
  notify:
    - restart apache
- name: Apache site
  template: dest=/etc/apache2/sites-available/{{ thefederation_domain }}.conf src=apache.conf.j2
- name: Enable site
  command: a2ensite {{ thefederation_domain }}
  notify:
    - restart apache
