---
- name: Get latest code
  git: accept_hostkey=yes dest="{{ thefederation_path }}" repo=https://github.com/jaywink/the-federation.info.git force=yes version={{ thefederation_version }}
  become_user: thefederation
  notify:
    - restart thefederation

- name: Set configuration
  template: dest="{{ thefederation_path }}/src/config.js" src=config.js.j2
  become_user: thefederation
  notify:
    - restart thefederation

- name: Install app requirements
  npm: path="{{ thefederation_path }}" production=yes
  become_user: thefederation
  notify:
    - restart thefederation

- name: Install upstart init
  template: dest=/etc/init/thefederation.conf src=upstart.conf.j2
  notify:
    - restart thefederation
