---
- name: Check for node.js repository
  stat: path=/etc/apt/sources.list.d/nodesource.list
  register: check_nodejs

- name: Install curl if needed
  apt: name=curl state=latest cache_valid_time=604800
  when: not check_nodejs.stat.exists

- name: Node.js repository
  shell: executable=/bin/bash /usr/bin/curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
  when: not check_nodejs.stat.exists
  
- name: System dependencies
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - git
    # Apache
    - apache2
    # Node
    - nodejs
