---
- name: System dependencies
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - git
    # Apache
    - apache2
    # Needed up geoip-lite
    - unzip
    # MySQL Python bindings
    - libmysqlclient-dev
