---
- name: The-Federation.info user
  user: name="{{ thefederation_os_user }}" state=present
- name: Ensure www-data member of thefederation group
  user: name=www-data append=yes groups="{{ thefederation_os_user }}" state=present
- name: Make thefederation home non-world readable
  file: path=/home/{{ thefederation_os_user }} mode=0750 state=directory
